# Generated by Django 5.2.15 on 2026-06-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('velocidad', models.FloatField(null=True)),
                ('ruta_id', models.IntegerField(null=True)),
                ('actualizado', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'buses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParadaTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
            options={
                'db_table': 'paradas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RutaParadaTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_id', models.IntegerField()),
                ('parada_id', models.IntegerField()),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ruta_paradas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RutaTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rutas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TramoVia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('lat_inicio', models.FloatField()),
                ('lng_inicio', models.FloatField()),
                ('lat_fin', models.FloatField()),
                ('lng_fin', models.FloatField()),
                ('radio_deteccion_metros', models.FloatField(default=150)),
                ('ruta_id', models.IntegerField(null=True)),
                ('ruta_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('ruta_color', models.CharField(blank=True, default='#3498db', max_length=20)),
                ('parada_inicio_id', models.IntegerField(null=True)),
                ('parada_fin_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'trafico_tramo_via',
                'unique_together': {('ruta_id', 'parada_inicio_id', 'parada_fin_id')},
            },
        ),
        migrations.CreateModel(
            name='EstadoTrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad_promedio', models.FloatField(default=0)),
                ('estado', models.CharField(choices=[('fluido', 'Fluido'), ('lento', 'Lento'), ('detenido', 'Detenido'), ('sin_datos', 'Sin datos')], default='sin_datos', max_length=20)),
                ('muestras', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tramo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual', to='trafico.tramovia')),
            ],
            options={
                'db_table': 'trafico_estado_actual',
            },
        ),
        migrations.CreateModel(
            name='LecturaVelocidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_placa', models.CharField(max_length=20)),
                ('velocidad', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='trafico.tramovia')),
            ],
            options={
                'db_table': 'trafico_lectura_velocidad',
                'indexes': [models.Index(fields=['tramo', 'timestamp'], name='trafico_lec_tramo_i_f61fd3_idx')],
            },
        ),
    ]
